services:
  - type: web
    name: nishad-brand-store
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nishad-brand-db
          property: connectionString
      - key: DATABASE_SSL
        value: "true"
      - key: NODE_ENV
        value: production
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
        sync: false
        sync: false
        sync: false
      - key: WHATSAPP_NUMBER
        value: "9296271001"
      - key: SITE_NAME
        value: "NISHAD BRAND"
      - key: UPI_VPA
        sync: false
      - key: UPI_NAME
        value: "NISHAD BRAND"

databases:
  - name: nishad-brand-db
    plan: free
